[package]
name = "sqlx-repro"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
tokio = { version = "1.39", features = ["macros", "rt-multi-thread"] }
sqlx = { version = "0.8", features = [
  "macros",
  "mysql",
  "runtime-tokio-rustls",
  "uuid",
] }
uuid = "1"
dotenvy = "0.15.7"
