services:
  database:
    image: mariadb:11.0
    environment:
      MARIADB_USER: foo
      MARIADB_PASSWORD: foo
      MARIADB_DATABASE: test
      MARIADB_ROOT_PASSWORD: foo
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - ./database:/var/lib/mysql
